SELECT
    hdr.WO_NUMBER AS WO_Number,
    pm.DESCRIPTION AS PART_DESCRIPTION,
    det.ITEM_NUMBER AS Item_Number,
    cwe.REF_DOCS_USED as REF_DOCS,
    COALESCE(det.DAMAGE_PART_DESCRIPTION, ' ') AS Problem_Description,
    COALESCE(det.CMM_REVISION, ' ') AS REVISION,
    cmp.COMPANY_NAME AS Customer,  -- This gets the Customer name based on CMP_AUTO_KEY match
    wo.COMPANY_REF_NUMBER AS Customer_RO,
    COALESCE(hdr.PN, ' ') AS Part_Number,
    COALESCE(hdr.SERIAL_NUMBER, ' ') AS Serial_Number,
    COALESCE(ero.REMARKS, ' ') AS Remarks,
    COALESCE(det.MECHANNIC, ' ') AS Requested_by,
    NVL(TO_DATE(TO_CHAR(det.MECHANNIC_DATE, 'YYYY-MM-DD'), 'YYYY-MM-DD'), TO_DATE('1970-01-01', 'YYYY-MM-DD')) AS Requested_Date,
    COALESCE(cwe.REPAIR_TYPE, ' ') AS REPAIR_TYPE,
    COALESCE(cwe.REPAIR_TYPE_PER, ' ') AS REPAIR_TYPE_PER,
    COALESCE(cwe.ACTION_REQUESTED, ' ') AS ACTION_REQUESTED,
    COALESCE(cwe.STRUCT_CLASF, ' ') AS STRUCT_CLASF,
    COALESCE(cwe.AMOC_REQ, ' ') AS AMOC_REQ,
    COALESCE(cwe.FCBS_NOTE, ' ') AS FCBS_NOTE,
    COALESCE(cwe.CRITICAL_COMPONENT, ' ') AS CRITICAL_COMPONENT,
    COALESCE(cwe.EASA_APROV_REQ, ' ') AS EASA_APROV_REQ,
    COALESCE(cwe.FAA_APROV_REQ, ' ') AS FAA_APROV_REQ,
    COALESCE(cwe.AMOC_REQ, ' ') AS AMOC_REQ,
    COALESCE(cwm.ORIG_MATERIAL, ' ') AS ORIG_MATERIAL,
    COALESCE(cwm.REPAIR_MATERIAL, ' ') AS REPAIR_MATERIAL,
    COALESCE(cwm.PO_RO, ' ') AS PO_RO,
    MAX(rep.ERO_NUMBER) AS ERO_Number,  -- Use MAX to ensure only one row is returned
    COALESCE(ac.APPLICATION_CODE, ' ') AS AC_Model,
    MAX(CASE WHEN aq.SEQUENCE = 1.1 THEN aq.QUESTION END) AS Question_1,
    MAX(CASE WHEN aq.SEQUENCE = 1.1 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_1,
    MAX(CASE WHEN aq.SEQUENCE = 1.2 THEN aq.QUESTION END) AS Question_2,
    MAX(CASE WHEN aq.SEQUENCE = 1.2 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_2,
    MAX(CASE WHEN aq.SEQUENCE = 1.3 THEN aq.QUESTION END) AS Question_3,
    MAX(CASE WHEN aq.SEQUENCE = 1.3 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_3,
    MAX(CASE WHEN aq.SEQUENCE = 1.4 THEN aq.QUESTION END) AS Question_4,
    MAX(CASE WHEN aq.SEQUENCE = 1.4 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_4,
    MAX(CASE WHEN aq.SEQUENCE = 1.5 THEN aq.QUESTION END) AS Question_5,
    MAX(CASE WHEN aq.SEQUENCE = 1.5 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_5,
    MAX(CASE WHEN aq.SEQUENCE = 1.6 THEN aq.QUESTION END) AS Question_6,
    MAX(CASE WHEN aq.SEQUENCE = 1.6 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_6,
    MAX(CASE WHEN aq.SEQUENCE = 2 THEN aq.QUESTION END) AS Question_7,
    MAX(CASE WHEN aq.SEQUENCE = 2 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_7,
    MAX(CASE WHEN aq.SEQUENCE = 3 THEN aq.QUESTION END) AS Question_8,
    MAX(CASE WHEN aq.SEQUENCE = 3 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_8,
    MAX(CASE WHEN aq.SEQUENCE = 4 THEN aq.QUESTION END) AS Question_9,
    MAX(CASE WHEN aq.SEQUENCE = 4 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_9,
    MAX(CASE WHEN aq.SEQUENCE = 5 THEN aq.QUESTION END) AS Question_10,
    MAX(CASE WHEN aq.SEQUENCE = 5 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_10,
    MAX(CASE WHEN aq.SEQUENCE = 6 THEN aq.QUESTION END) AS Question_11,
    MAX(CASE WHEN aq.SEQUENCE = 6 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_11,
    MAX(CASE WHEN aq.SEQUENCE = 7 THEN aq.QUESTION END) AS Question_12,
    MAX(CASE WHEN aq.SEQUENCE = 7 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_12,
    MAX(CASE WHEN aq.SEQUENCE = 8 THEN aq.QUESTION END) AS Question_13,
    MAX(CASE WHEN aq.SEQUENCE = 8 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_13,
    MAX(CASE WHEN aq.SEQUENCE = 9 THEN aq.QUESTION END) AS Question_14,
    MAX(CASE WHEN aq.SEQUENCE = 9 THEN CASE WHEN aq.ANSWER = 'N' THEN 'NO' WHEN aq.ANSWER = 'Y' THEN 'YES' ELSE ' ' END END) AS Answer_14,
    CASE
        WHEN 
            MAX(CASE WHEN aq.SEQUENCE = 1.1 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 1.2 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 1.3 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 1.4 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 1.5 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 1.6 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 2 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 3 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 4 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 5 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 6 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 7 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 8 THEN aq.ANSWER END) = 'YES' OR
            MAX(CASE WHEN aq.SEQUENCE = 9 THEN aq.ANSWER END) = 'YES'
        THEN 'MAJOR'
        ELSE 'MINOR'
    END AS Action_Type
FROM
    CRG_WO_FINDINGS_HEADER hdr
JOIN
    CRG_WO_FINDINGS_DETAIL det ON hdr.WOFH_ID = det.WOFH_ID
LEFT JOIN
    gatcrgqctl.COMPANIES@prod.gatelesis.com cmp ON hdr.CMP_AUTO_KEY = cmp.CMP_AUTO_KEY  -- Join to get Customer name
LEFT JOIN
    gatcrgqctl.WO_OPERATION@prod.gatelesis.com wo ON hdr.WO_NUMBER = wo.SI_NUMBER
JOIN
    CRG_WO_ERO ero ON det.WOF_ID = ero.WOF_ID
JOIN 
    CRG_WO_ERO_PHASES cwe ON ero.EROR_ID = cwe.EROR_ID
JOIN 
    CRG_WO_EROP_QTH_APPLIED qth ON cwe.EROP_ID = qth.EROP_ID
JOIN 
    CRG_WO_EROP_QTD_APPLIED aq ON qth.EROP_QTHAP_ID = aq.EROP_QTHAP_ID
LEFT JOIN 
    CRG_WO_EROP_MATERIAL cwm ON cwe.EROP_ID = cwm.EROP_ID
LEFT JOIN
    CRG_WO_REP_DISPOSITION rep ON cwe.EROR_ID = rep.EROR_ID
LEFT JOIN
    gatcrgqctl.PARTS_MASTER@prod.gatelesis.com pm ON hdr.PNM_AUTO_KEY = pm.PNM_AUTO_KEY  -- Join to get APC_AUTO_KEY
LEFT JOIN
    gatcrgqctl.APPLICATION_CODES@prod.gatelesis.com ac ON pm.APC_AUTO_KEY = ac.APC_AUTO_KEY  -- Join to get APPLICATION_CODE
WHERE
    cwe.EROP_ID = $P{P_EROP_ID}
GROUP BY 
    hdr.WO_NUMBER, det.ITEM_NUMBER, cmp.COMPANY_NAME, wo.COMPANY_REF_NUMBER,
    hdr.PN, hdr.SERIAL_NUMBER, ero.REMARKS, det.MECHANNIC, det.MECHANNIC_DATE,
    cwe.REPAIR_TYPE, cwe.REPAIR_TYPE_PER, cwe.ACTION_REQUESTED, cwe.STRUCT_CLASF,
    cwe.AMOC_REQ, cwe.FCBS_NOTE, cwe.CRITICAL_COMPONENT, cwe.EASA_APROV_REQ,
    cwe.FAA_APROV_REQ, cwm.ORIG_MATERIAL, cwm.REPAIR_MATERIAL, cwm.PO_RO, hdr.WOFH_ID,ac.APPLICATION_CODE,pm.DESCRIPTION,det.CMM_REVISION,det.DAMAGE_PART_DESCRIPTION,
    cwe.REF_DOCS_USED